<?php
// Generated by Zend Framework 2
return array(
    'UthandoTwitter\Module'                 => __DIR__ . '/Module.php',
    'UthandoTwitter\Model\Tweet'            => __DIR__ . '/src/UthandoTwitter/Model/Tweet.php',
    'UthandoTwitter\Model\TweetCollection'  => __DIR__ . '/src/UthandoTwitter/Model/TweetCollection.php',
    'UthandoTwitter\Service\Twitter'        => __DIR__ . '/src/UthandoTwitter/Service/Twitter.php',
    'UthandoTwitter\Service\TwitterFactory' => __DIR__ . '/src/UthandoTwitter/Service/TwitterFactory.php',
    'UthandoTwitter\View\TweetFeed'         => __DIR__ . '/src/UthandoTwitter/View/TweetFeed.php',
);